import "./App.scss";
import React, { useRef, useState } from "react";
import StoryModal from "./components/StoryModal";
import InputForm from "./components/InputForm";

// App component is the main component of the application
function App() {
  // State for the generated story
  const [story, setStory] = useState(null);
  // Reference for the InputForm component
  const inputFormRef = useRef();

  // This function is called when the server sends the entire story via a single response
  // Handle the story generated by the server
  const handleStoryGenerated = (story) => {
    setStory(story);
  };

  // This function is called when the server sends a new story part via a streaming response
  // Handle the story part received from the server via streaming
  const handleStoryPartReceived = (storyPart) => {
    setStory(storyPart);
  };

  // This function is called when the user closes the story modal and the animation has finished
  // Handle the story modal closed event
  const handleStoryModalClosed = () => {
    setStory(null);
  };

  // This function is called when the user clicks the "Regenerate" button in the story modal
  // Handle the regenerate story request
  const handleRegenerate = () => {
    inputFormRef.current.cancelRequest();
    inputFormRef.current.submitForm();
  };

  return (
    <div className="App">
      <div className="app-content">
        <InputForm
          ref={inputFormRef}
          onStoryPartReceived={handleStoryPartReceived}
          onStoryGenerated={handleStoryGenerated}
        />
        {story && (
          <StoryModal
            story={story}
            onRegenerate={handleRegenerate}
            onCloseComplete={handleStoryModalClosed}
            onCancelRequest={inputFormRef.current.cancelRequest}
          />
        )}
      </div>
    </div>
  );
}

export default App;
